---
# Set java_packages if you would like to use a different version than the
# default for the OS (see defaults per OS in `vars` directory).
# java_packages: []

java_home: ""

elasticsearch_version: '7.x'
elasticsearch_package: elasticsearch
elasticsearch_package_state: present

elasticsearch_service_state: started
elasticsearch_service_enabled: true

elasticsearch_network_host: localhost
elasticsearch_http_port: 9200

elasticsearch_heap_size_min: 1g
elasticsearch_heap_size_max: 2g

elasticsearch_extra_options: ''

kibana_version: "7.x"

kibana_package: kibana
kibana_package_state: present

kibana_service_state: started
kibana_service_enabled: true

kibana_config_template: kibana.yml.j2
kibana_config_file_path: /etc/kibana/kibana.yml

kibana_server_port: 5601
kibana_server_host: "0.0.0.0"

kibana_elasticsearch_url: "http://localhost:9200"
kibana_elasticsearch_username: ""
kibana_elasticsearch_password: ""
